[codedeploy] 설정 시작

diff --git a/.github/workflows/commit-stage.yml b/.github/workflows/commit-stage.yml
--- a/.github/workflows/commit-stage.yml
+++ b/.github/workflows/commit-stage.yml
@@ -50,50 +50,50 @@ jobs:
         run: |                                    # 윈도우 호환성 해결, 그래들 스크립트를 실행 가능하게 
           chmod +x gradlew          
           ./gradlew build
-  package:
-    name: Package and Publish
-    if: ${{ github.ref == 'refs/heads/master' }}  # 잡을 master 브랜치에 대해서만 실행
-    needs: [ build ] # 'build' 잡이 성공적으로 수행된 경우에만 이 잡을 실행
-    runs-on: ubuntu-22.04
-    permissions:
-      contents: read  # 현재 깃 저장소를 체크아웃하기 위한 권한
-      packages : write # 깃허브 컨테이너 저장소로 이미지를 업로드하기 위한 권한
-      security-events: write  # 깃허브로 보안 이벤트를 제출하기 위한 권한
-    steps:
-      - name: Checkout source code
-        uses: actions/checkout@v4 # 현재 깃 저장소(catalog-service) 를 체크아웃한다.
-      - name: Set up JDK
-        uses: actions/setup-java@v4  # 자바 런타임을 설치하고 설정한다
-        with:
-          distribution: temurin
-          java-version: 17
-          cache: gradle
-      - name: Build container image
-        run : |
-          chmod +x gradlew
-          ./gradlew bootBuildImage \
-            --imageName ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
-      - name: OCI image vulnerability scanning
-        uses: anchore/scan-action@v3  # 취약성 검사를 위해 그라이프를 사용해 릴리스 후보 이미지를 스캔한다.
-        id: scan
-        with: # 스캔할 이미지는 릴리스 후보다.
-          image:  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
-          fail-build: false
-          severity-cutoff: high
-          acs-report-enable: true
-      - name: Upload vulnerability report
-        uses: github/codeql-action/upload-sarif@v3  # 깃허브로 보안 취약성 리포트를 업로드
-        if: success() || failure()
-        with:
-          sarif_file: ${{ steps.scan.outputs.sarif }}
-      - name: Log into container registry
-        uses: docker/login-action@v3
-        with:
-          registry: ${{ env.REGISTRY }}
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }} # 저장소와 인증하기 위해 필요한 토큰. 깃허브 액션이 제공 함
-      - name: Publish container image # 릴리스 후보를 저장소로 푸시
-        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
+#  package:
+#    name: Package and Publish
+#    if: ${{ github.ref == 'refs/heads/master' }}  # 잡을 master 브랜치에 대해서만 실행
+#    needs: [ build ] # 'build' 잡이 성공적으로 수행된 경우에만 이 잡을 실행
+#    runs-on: ubuntu-22.04
+#    permissions:
+#      contents: read  # 현재 깃 저장소를 체크아웃하기 위한 권한
+#      packages : write # 깃허브 컨테이너 저장소로 이미지를 업로드하기 위한 권한
+#      security-events: write  # 깃허브로 보안 이벤트를 제출하기 위한 권한
+#    steps:
+#      - name: Checkout source code
+#        uses: actions/checkout@v4 # 현재 깃 저장소(catalog-service) 를 체크아웃한다.
+#      - name: Set up JDK
+#        uses: actions/setup-java@v4  # 자바 런타임을 설치하고 설정한다
+#        with:
+#          distribution: temurin
+#          java-version: 17
+#          cache: gradle
+#      - name: Build container image
+#        run : |
+#          chmod +x gradlew
+#          ./gradlew bootBuildImage \
+#            --imageName ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
+#      - name: OCI image vulnerability scanning
+#        uses: anchore/scan-action@v3  # 취약성 검사를 위해 그라이프를 사용해 릴리스 후보 이미지를 스캔한다.
+#        id: scan
+#        with: # 스캔할 이미지는 릴리스 후보다.
+#          image:  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
+#          fail-build: false
+#          severity-cutoff: high
+#          acs-report-enable: true
+#      - name: Upload vulnerability report
+#        uses: github/codeql-action/upload-sarif@v3  # 깃허브로 보안 취약성 리포트를 업로드
+#        if: success() || failure()
+#        with:
+#          sarif_file: ${{ steps.scan.outputs.sarif }}
+#      - name: Log into container registry
+#        uses: docker/login-action@v3
+#        with:
+#          registry: ${{ env.REGISTRY }}
+#          username: ${{ github.actor }}
+#          password: ${{ secrets.GITHUB_TOKEN }} # 저장소와 인증하기 위해 필요한 토큰. 깃허브 액션이 제공 함
+#      - name: Publish container image # 릴리스 후보를 저장소로 푸시
+#        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
   deploy:
     name: Deploy
     runs-on: ubuntu-latest
